# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
