# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmoinaug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('ok', 'Accepted'), ('no', 'Rejected'), ('pe', 'Pending')], default='pe', max_length=2),
        ),
    ]
