# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmoinaug', '0002_auto_20180412_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('ok', 'Approved'), ('no', 'Rejected'), ('pe', 'Pending')], default='pe', max_length=2),
        ),
    ]
