# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctmoinaug', '0003_auto_20180412_2100'),
        ('ctmoinaug', '0003_auto_20180416_1658'),
    ]

    operations = [
    ]
