# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligo_run', models.CharField(blank=True, max_length=20, null=True, verbose_name='LIGO run')),
                ('grace_id', models.CharField(max_length=20, verbose_name='GraceDB ID')),
                ('alert_number', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('is_taken', models.BooleanField(default=False)),
                ('was_observed', models.BooleanField(default=False)),
                ('probability', models.FloatField(blank=True, default=0.0, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Alert')),
            ],
        ),
        migrations.CreateModel(
            name='GWGCCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgc', models.IntegerField(verbose_name='PGC Identifier from HYPERLEDA')),
                ('name', models.CharField(max_length=20, verbose_name='Common Name')),
                ('ra', models.FloatField(blank=True, null=True, verbose_name='Right Ascension')),
                ('dec', models.FloatField(blank=True, null=True, verbose_name='Declination')),
                ('obj_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Type')),
                ('app_mag', models.FloatField(blank=True, null=True, verbose_name='Apparent Blue Magnitude')),
                ('maj_diam_a', models.FloatField(blank=True, null=True, verbose_name='Major Diameter(a)')),
                ('err_maj_diam', models.FloatField(blank=True, null=True, verbose_name='Error in Major Diameter')),
                ('min_diam_b', models.FloatField(blank=True, null=True, verbose_name='Minor diameter (b) ')),
                ('err_min_diam', models.FloatField(blank=True, null=True, verbose_name='Error in Minor diameter')),
                ('b_over_a', models.FloatField(blank=True, null=True, verbose_name='b/a(Ratio of minor to major diameters) ')),
                ('err_b_over_a', models.FloatField(blank=True, null=True, verbose_name='Error b/a (Ratio of minor to major diameters)')),
                ('pa', models.FloatField(blank=True, null=True, verbose_name='Position Angle of Galaxy')),
                ('abs_mag', models.FloatField(blank=True, null=True, verbose_name='Absolute Blue Magnitude')),
                ('dist', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('err_dist', models.FloatField(blank=True, null=True, verbose_name='Error on Distance')),
                ('err_app_mag', models.FloatField(blank=True, null=True, verbose_name='Error on Apparent blue magnitude')),
                ('err_abs_mag', models.FloatField(blank=True, null=True, verbose_name='Error on Absolute blue magnitude')),
            ],
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'observatories',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='observatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Observatory'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.GWGCCatalog'),
        ),
    ]
