# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:50
from __future__ import unicode_literals

import os
from django.db import migrations
from django.core import serializers


fixture_dir = os.path.join(os.path.dirname(__file__), '../fixtures')
fixture_filename = 'gwgc.json'

def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()

def unload_fixture(apps, schema_editor):
    "Delete all entries for GWGCCatalog"
    MyModel = apps.get_model("broker", "GWGCCatalog")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
