# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_load_gwgc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCNNotice',
            options={'verbose_name': 'GCN Notice', 'verbose_name_plural': 'GCN Notices'},
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcnorigin', models.CharField(choices=[('GW', 'Gravitational Wave'), ('GRB', 'Gamma Ray Burst'), ('OTH', 'Other')], default='GW', max_length=3, verbose_name='GCN Origin')),
                ('gcntype', models.IntegerField(choices=[(0, 'Preliminary'), (1, 'Initial'), (2, 'Update'), (3, 'Retraction')], default=0, verbose_name='GCN Type')),
                ('superevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Alert', verbose_name='Super Event')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
