# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_gcnnotice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='SuperEvent',
        ),
    ]
