# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_rename_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='gcnnotice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.GCNNotice'),
        ),
    ]
