# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 01:23
from __future__ import unicode_literals

from django.db import migrations


def update_gcnnotice(apps, schema_editor):
    SuperEvent = apps.get_model('broker', 'SuperEvent')
    GCNNotice = apps.get_model('broker', 'GCNNotice')
    for event in SuperEvent.objects.all():
        notice = GCNNotice(gcnorigin='GW', gcntype=1, superevent=event, datetime=event.datetime)
        notice.save()

    Assignment = apps.get_model('broker', 'Assignment')
    for assgn in Assignment.objects.all():
        gcnnotice = assgn.alert.gcnnotice_set.first()
        assgn.gcnnotice = gcnnotice
        assgn.save()


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_add_assignment_gcnnotice'),
    ]

    operations = [
        migrations.RunPython(update_gcnnotice),
    ]
