# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_create_gcnnotices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gcnnotice',
            field=models.ForeignKey(null=False, to='broker.GCNNotice'),
        ),
    ]
