# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_gcnnotice_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='alert',
        ),
    ]
