# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_remove_assignment_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superevent',
            name='alert_number',
        ),
        migrations.AddField(
            model_name='superevent',
            name='se_type',
            field=models.CharField(choices=[('T', 'Test'), ('M', 'Mock'), ('S', 'Production'), ('D', 'Drill')], default='S', max_length=1, verbose_name="Super Event type"),
        ),
        migrations.AddField(
            model_name='superevent',
            name='was_confirmed_GW',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superevent',
            name='was_retracted',
            field=models.BooleanField(default=False),
        ),
    ]
