# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_auto_20181231_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superevent',
            name='grace_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='GraceDB ID'),
        ),
    ]
