# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_auto_20190104_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superevent',
            name='se_type',
            field=models.CharField(choices=[('T', 'Test'), ('M', 'Mock'), ('S', 'Observation'), ('D', 'Drill')], default='S', max_length=1, verbose_name='Super Event type'),
        ),
    ]
