# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_auto_20190107_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GWGCCatalog',
            new_name='SourceCatalog',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='b_over_a',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='err_b_over_a',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='err_maj_diam',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='err_min_diam',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='maj_diam_a',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='min_diam_b',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='pa',
        ),
        migrations.RenameField(
            model_name='sourcecatalog',
            old_name='app_mag',
            new_name='b_mag',
        ),
        migrations.RenameField(
            model_name='sourcecatalog',
            old_name='err_app_mag',
            new_name='b_err',
        ),
        migrations.RenameField(
            model_name='sourcecatalog',
            old_name='abs_mag',
            new_name='b_abs',
        ),
        migrations.RenameField(
            model_name='sourcecatalog',
            old_name='err_dist',
            new_name='dist_err',
        ),
        migrations.RemoveField(
            model_name='sourcecatalog',
            name='err_abs_mag',
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='b_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='Apparent B Magnitude'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='b_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Error on Apparent B Magnitude'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='b_abs',
            field=models.FloatField(blank=True, null=True, verbose_name='Absolute B Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='h_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Error on Apparent H Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='h_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='Apparent H Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='j_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Error on Apparent J Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='j_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='Apparent J Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='k_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Error on Apparent K Magnitude'),
        ),
        migrations.AddField(
            model_name='sourcecatalog',
            name='k_mag',
            field=models.FloatField(blank=True, null=True, verbose_name='Apparent K Magnitude'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='pgc',
            field=models.IntegerField(blank=True, null=True, verbose_name='PGC Identifier from HYPERLEDA'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='Right Ascension [deg]'),
        ),
        migrations.AlterField(
            model_name='sourcecatalog',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Declination [deg]'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.SourceCatalog'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
