# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-06 19:28
from __future__ import unicode_literals

import os
from django.db import migrations, models


def fill_target_name(apps, schema_editor):
    SourceCatalog = apps.get_model("broker", "SourceCatalog")
    Assignment = apps.get_model("broker", "Assignment")
    for assn in Assignment.objects.all():
        assn.target_name = assn.target.name
        assn.save()

class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0013_gwgc_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='target_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(fill_target_name),
    ]
