# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def reassign_target(apps, schema_editor):
    Assignment = apps.get_model("broker", "Assignment")
    SourceCatalog = apps.get_model("broker", "SourceCatalog")
    for assgn in Assignment.objects.all():
        try:
            target = SourceCatalog.objects.get(name=assgn.target_name)
            assgn.target = target
            assgn.save()
        except:
            created, target = SourceCatalog.objects.get_or_create(
                name="MISSING",
                defaults={'ra': 0.0, 'dec': 0.0},
                )
            assgn.target = target
            assgn.save()
            print("Couldn't find {} on catalog. Assigning to MISSING object."
                  .format(assgn.target_name))


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_preserve_target_in_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecatalog',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Common Name'),
        ),
        migrations.RunPython(reassign_target),
        migrations.RemoveField(
            model_name='assignment',
            name='target_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.SourceCatalog'),
        ),
    ]
