# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models


def correct_serial_number(apps, schema_editor):
    GCNNotice = apps.get_model("broker", "GCNNotice")
    SuperEvent = apps.get_model("broker", "SuperEvent")
    for event in SuperEvent.objects.all():
        sn = 0
        for notice in GCNNotice.objects.filter(superevent=event).order_by("datetime"):
            sn = sn + 1
            notice.serialnumber = sn
            notice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_reassign_target_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcnnotice',
            name='serialnumber',
            field=models.IntegerField(default=1, help_text='Pkt_Ser_Num: A serial number for the GCN'),
        ),
        migrations.RunPython(correct_serial_number),
    ]
