# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_reassign_target_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcnnotice',
            name='serialnumber',
            field=models.IntegerField(default=1, help_text='Pkt_Ser_Num: A serial number for the GCN'),
        ),
    ]
