# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('torosweb', '0001_homepage_infopage_newsindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindex',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
