# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-23 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torosweb', '0002_newsindex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindex',
            name='news_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
