# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:35
from __future__ import unicode_literals

from django.db import migrations


def create_group(apps, schema_editor):
    from django.contrib.auth.models import Group
    wiki_editors_group, created = Group.objects.get_or_create(name='wiki_editors')


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to')
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
